### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by tigerzhang** [hlc1209/RT-NRVE#1]
Thanks for you great work!

Is there a pre-trained model which I can download, I want to have test on it.

Thanks again.

**Comment by hlc1209** [comment]
Here you go
https://github.com/hlc1209/RT-NRVE/blob/main/model_pretrained.h5
This is a very old project that's still in early stage. Despite this, I'm looking forward to hearing your thoughts on it.

**Comment by tigerzhang** [comment]
Thank you.

I came across your video on Youtube. The performance of your model is impressive.
